
- hosts: localhost
  # become: true
  # become_method: sudo
  tasks:
    - name: Add host to group 'just_created' with variable foo=42
      add_host:
        name: 65.1.110.217
        groups: just_created
        foo: 42

- hosts: just_created
  # become: true
  # become_method: sudo
  gather_facts: no
  tasks:

    - name: copy the docker compose to remote
      copy:
        src: "/home/ubuntu/actions-runner/_work/{{ repo_name }}/{{ repo_name }}/docker-compose.yml"
        dest: /home/ubuntu/{{ repo_name }}/
        mode: 0766