name: Build and Deployment
on: 
    push:
        branches:
            - 'main'
            - 'feature*'
            - 'feature/*'
        # branches-ignore:
        #     - 'release*'
        #     - 'release/*'
jobs:
    test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'oracle' # See 'Supported distributions' for available options
                java-version: '11'
            - name: Maven Package
              run: mvn -B clean package -DskipTests
            - name: Maven Verify
              run: mvn -B clean verify

